export const tenantProfile = {
  name: 'Rumo ao Esporte',
  displayName: 'Rumo ao Esporte',
  state: 'MG',
  businessType: 'Escola de esportes',
  primaryColor: '#17428f',
  logoUrl: '/rumo-ao-esporte-logo.png',
  requestedAt: '15/06/2026, 12:16',
  studentsRange: 'Até 100',
  classes: 'Não informado',
  currentControl: 'Não informado',
  modalities: ['Futebol'],
  users: [],
  modules: [
    'Financeiro/cobranças',
    'Mensagens/WhatsApp',
    'Portal do aluno/responsável',
    'Turmas e horários',
    'Carteirinhas/identificação',
    'Cadastro de alunos/responsáveis',
  ],
  mainPain: 'Financeiro/cobrança',
  priority: 'Financeiro/cobranças',
  deadline: 'Urgente',
  contact: {
    name: 'Éder de Assis Albergaria',
    phone: '(33) 99802-1002',
    email: 'ederalbergaria16@hotmail.com',
  },
} as const;
